### ISSUE TITLE
Add Airline theme

### ISSUE THREAD

**Issue by otommod** [fneu/breezy#1]
Given that there's a Lightline theme, I don't think this would be much more work...

I could try do it myself if you want.

**Comment by fneu** [comment]
Sure, let's do this. Airline's themes seem to involve a little more magic, best documentation seems to be [this](https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/themes/dark.vim) commented example. It's gotten late over here but I can look into this tomorrow.

**Comment by fneu** [comment]
I've added a basic airline theme as of today. Thank you for the suggestion, feel free to contribute refinements if you like.

**Comment by otommod** [comment]
Oh this is really nice, thank you!
And thank you for the awesome theme as well!
